name: Playwright Tests 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Fix node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Versions
        run: |
          echo "Printing versions:"
          echo "node version:"
          node --version
          echo "npm version:"
          npm --version
          lsb_release -a

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests --reporter=html

      - name: List all files
        run: ls -R
	  
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30